services:
    alpha_sim1: 
        image: nvidia/cuda:11.6.0-devel-ubuntu18.04
        stdin_open: true
        tty: true
        build: .
        user: agv
        privileged: true
        environment: 
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        volumes: 
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ./src:/home/agv/alpha_ws/src
        network_mode: host
        deploy: 
            resources: 
                reservations:
                    devices: 
                    -   driver: nvidia
                        count: all
                        capabilities: [gpu]

